# Main days-to-christmas function as On-Demand Builder
[functions]
  directory = "netlify/functions"

[[edge_functions]]
function = "single"
path = "/single"

[[edge_functions]]
function = "bday"
path = "/bday"